/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2023-01-02 12:16:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import cart.CartDao;
import member.MemberBean;
import member.MemberDao;
import category.CategoryBean;
import java.util.ArrayList;
import category.CategoryDao;

public final class userJoinView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/user/./top_user.jsp", Long.valueOf(1672659551000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.MemberDao");
    _jspx_imports_classes.add("category.CategoryDao");
    _jspx_imports_classes.add("category.CategoryBean");
    _jspx_imports_classes.add("cart.CartDao");
    _jspx_imports_classes.add("member.MemberBean");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	body, header {\r\n");
      out.write("	    font-size: 17px;\r\n");
      out.write("	    line-height: 1.25;\r\n");
      out.write("	    font-family: 'Noto Sans KR', AppleGothic, Helvetica, sans-serif;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	body {\r\n");
      out.write("	    background-color: #FFF;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	/* a태그 밑줄 없애기 */\r\n");
      out.write("	a {\r\n");
      out.write("  		text-decoration: none;\r\n");
      out.write("  		color: #1c1c1c;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	/* 리스트의 왼쪽 점 없애기 */\r\n");
      out.write("	li{\r\n");
      out.write("		list-style : none;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	/* 마우스 올리면 색깔 변하게 하기 */\r\n");
      out.write("	.tmenu > a:hover{\r\n");
      out.write("		color : gray;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	/* 최상단 헤더--------------*/\r\n");
      out.write("	.hd{\r\n");
      out.write("		width : 100%;\r\n");
      out.write("		background-color: #FFF;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.hd img{\r\n");
      out.write("		width : 247px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.hdRight li{\r\n");
      out.write("		float : right;\r\n");
      out.write("		margin : 10px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.hdRight a{\r\n");
      out.write("		font-size: 12px;\r\n");
      out.write("	}\r\n");
      out.write("	/* ----------------------*/\r\n");
      out.write("	\r\n");
      out.write("	/* 카테고리가 위치한 헤더-------------- */\r\n");
      out.write("	.hd2{\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		border-top: 1px solid black;\r\n");
      out.write("	}\r\n");
      out.write("	.hd2 td{\r\n");
      out.write("		height : 50px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.cateWrap, .searchWrap{\r\n");
      out.write("		text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.tmenu{\r\n");
      out.write("		position: relative; /* class = 'depth2'가 absolute 일 때 이것을 부모로 인식하도록 position을 지정해줌*/\r\n");
      out.write("		margin: 0px 10px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	/* 카테고리에 마우스 올렸을 때 화면에 뜨는 부분 */\r\n");
      out.write("	.depth2{\r\n");
      out.write("		position: absolute; /* 다른 요소에 영향을 주지않고 배치시키기 위함  */\r\n");
      out.write("		transform: translate(-50%,0%);\r\n");
      out.write("		right : 50%; \r\n");
      out.write("		left : 50%;\r\n");
      out.write("		top: 100%;\r\n");
      out.write("		width: 100px; \r\n");
      out.write("		padding-left: 0px;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("		padding-top: 10px;\r\n");
      out.write("		/* background-color: #FFF; */\r\n");
      out.write("		margin-top: 0;\r\n");
      out.write("		background-color: #FFF;\r\n");
      out.write("		\r\n");
      out.write("		/* border : 1px red solid; */\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.searchWrap{\r\n");
      out.write("		height : auto;\r\n");
      out.write("		display: flex;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.depth2 li{\r\n");
      out.write("		padding : 5px;\r\n");
      out.write("		font-size: 13px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.searchArea li{\r\n");
      out.write("		float : left;\r\n");
      out.write("		margin : 5px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.searchspan{\r\n");
      out.write("		position: relative; /* class = 'depth2'가 absolute 일 때 이것을 부모로 인식하도록 position을 지정해줌*/\r\n");
      out.write("		margin: 0px 0px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.searchspan input{\r\n");
      out.write("		width : 150px;\r\n");
      out.write("		border-radius: 8px;\r\n");
      out.write("		/* outline: red; */\r\n");
      out.write("		border: 1px #979797 solid; \r\n");
      out.write("		background: transparent;\r\n");
      out.write("		margin-top: 15px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.searchspan img{\r\n");
      out.write("		position : absolute;\r\n");
      out.write("		top: 0px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	.searchArea{\r\n");
      out.write("		height : auto;\r\n");
      out.write("		display: flex; /* 높이가 자동으로 0으로 설정된다면 사용해볼만한 설정 */\r\n");
      out.write("	}\r\n");
      out.write("	/* ----------------------*/\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"../js/jquery.js\"></script> -->\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write(" 		//카테고리 펼쳐지고 접히기\r\n");
      out.write("		jQuery(\".tmenu\").live(\"mouseenter\", function() {\r\n");
      out.write("		   jQuery(this).find(\".depth2\").slideDown(\"fast\");\r\n");
      out.write("		});\r\n");
      out.write("		jQuery(\".tmenu\").live(\"mouseleave\", function() {\r\n");
      out.write("		   jQuery(this).find(\".depth2\").slideUp(\"fast\");\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	function gotoCart(){\r\n");
      out.write("		");

		if(session.getAttribute("mno") == null){
      out.write("\r\n");
      out.write("			location.href = \"./loginView.jsp\";\r\n");
      out.write("		");
			
		}
		else{
		
      out.write("\r\n");
      out.write("			location.href = \"");
      out.print(request.getContextPath());
      out.write("/user/cart/showCart.jsp\";	\r\n");
      out.write("		");
	
		}
		
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("	<table class=\"hd\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td width=33%></td>\r\n");
      out.write("			<td width=33% align=\"center\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/user/main.jsp\" class=\"hd_logo\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/images/title.png\" style=\"height:40px; width:230px\"></a></td>\r\n");
      out.write("			\r\n");
      out.write("			<td width=33% align=\"right\">\r\n");
      out.write("				<ul class=\"hdRight\">\r\n");
      out.write("					<li>\r\n");
      out.write("						<a href=\"javascript:gotoCart()\">\r\n");
      out.write("						CART<span class=\"bsCount\">(<span id=\"user_basket_quantity\" class=\"user_basket_quantity\">\r\n");
      out.write("						");

						int result = 0;
						if(session.getAttribute("mno") != null){
							int mno = (int)session.getAttribute("mno");
							CartDao ctdao = CartDao.getInstance();
							result = ctdao.countItemInCart(mno);	
						}
						
      out.write("\r\n");
      out.write("						\r\n");
      out.write("						");
      out.print(result);
      out.write("\r\n");
      out.write("						\r\n");
      out.write("						</span>)</span>\r\n");
      out.write("						</a>\r\n");
      out.write("					</li>\r\n");
      out.write("					\r\n");
      out.write("					");

						MemberDao mdao = MemberDao.getInstance();
						
						String mid = (String)session.getAttribute("mid");
						
						if(mid == null){ // 로그인을 하지 않은 상태
						
      out.write("\r\n");
      out.write("							\r\n");
      out.write("							<li><a href=\"./userJoinView.jsp\">JOIN</a></li>\r\n");
      out.write("							<li><a href=\"./loginView.jsp\">LOGIN</a></li>\r\n");
      out.write("						");
							
						}
						else{ // 로그인 상태
							
							MemberBean mbean = mdao.getMemberById(mid);
							
							
      out.write("\r\n");
      out.write("								\r\n");
      out.write("								<li><a href=\"/shop/member.html?type=mynewmain\">MYPAGE</a></li>\r\n");
      out.write("								<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/user/logoutProc.jsp\">LOGOUT</a></li>\r\n");
      out.write("							");

						
							if(mid.equals("admin")){
      out.write("\r\n");
      out.write("								<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/categoryManage/categoryManage.jsp\">MANAGE</a></li>\r\n");
      out.write("							");
	
							}
							
							
      out.write("\r\n");
      out.write("							\r\n");
      out.write("							<li><a>");
      out.print(mbean.getName());
      out.write("님</a></li>\r\n");
      out.write("							\r\n");
      out.write("							");

						}
						
						
						
					
      out.write("\r\n");
      out.write("					<!-- <li><a href=\"https://www.jogunshop.com/shop/idinfo.html?type=new&amp;mem_type=person&amp;first=\">JOIN</a></li>\r\n");
      out.write("					<li><a href=\"./login/loginView.jsp\">LOGIN</a></li> -->\r\n");
      out.write("				</ul>\r\n");
      out.write("			</td>\r\n");
      out.write("		<tr>\r\n");
      out.write("	</table>\r\n");
      out.write("	\r\n");
      out.write("	<!-- <hr> -->\r\n");
      out.write("	<table class=\"hd2\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td width=\"20%\"></td>\r\n");
      out.write("			<td width=\"60%\">\r\n");
      out.write("				<!-- 카테고리 -->\r\n");
      out.write("				<div class=\"cateWrap\">\r\n");
      out.write("					\r\n");
      out.write("					");

						CategoryDao cdao = CategoryDao.getInstance();	
						ArrayList<CategoryBean> clist = cdao.getAllCategory();
							
						String beforeLname = "";
						
						for(int i = 0; i<clist.size() ;i++){
							CategoryBean cbean = clist.get(i);
							
							if(cbean.getSstep() == 1 || cbean.getSname() == null){
      out.write("\r\n");
      out.write("									</ul>\r\n");
      out.write("								</span>\r\n");
      out.write("							");
 
							}
							
							if(beforeLname.equals(cbean.getLname()) == false && (cbean.getSstep() == 1 || cbean.getSname() == null) && cbean.getLstep() != 0){// 대분류 명일때
							
      out.write("\r\n");
      out.write("								<span class=\"tmenu\"> <a href=\"");
      out.print(request.getContextPath());
      out.write("/user/showLargeCategory.jsp?lcno=");
      out.print(cbean.getLno());
      out.write('"');
      out.write('>');
      out.print(cbean.getLname() );
      out.write("</a>\r\n");
      out.write("									<ul class=\"depth2\" style=\"display: none;\">\r\n");
      out.write("							");
	
							}
							
							if(cbean.getSname() != null){
      out.write("\r\n");
      out.write("								<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/user/showSmallCategory.jsp?scno=");
      out.print(cbean.getSno());
      out.write('"');
      out.write('>');
      out.print(cbean.getSname() );
      out.write("</a></li>\r\n");
      out.write("							");
	
							}

							beforeLname = cbean.getLname();
						}
					
					
      out.write("\r\n");
      out.write("					\r\n");
      out.write("			\r\n");
      out.write("					<!-- <span class=\"tmenu\"> \r\n");
      out.write("					<a href=\"/shop/shopbrand.html?xcode=071&amp;type=P\"><font color=#C2674B>BEST</font></a>\r\n");
      out.write("					</span> \r\n");
      out.write("					\r\n");
      out.write("					<span class=\"tmenu\"> <a href=\"/shop/shopbrand.html?xcode=078&amp;type=Y\">TOP</a>\r\n");
      out.write("						<ul class=\"depth2\" style=\"display: none;\">\r\n");
      out.write("							<li><a href=\"/shop/shopbrand.html?xcode=078&amp;type=N&amp;mcode=010\">반팔티</a></li>\r\n");
      out.write("							<li><a href=\"/shop/shopbrand.html?xcode=078&amp;type=N&amp;mcode=003\">나시</a></li>\r\n");
      out.write("							<li><a href=\"/shop/shopbrand.html?xcode=078&amp;type=N&amp;mcode=002\">프린팅티</a></li>\r\n");
      out.write("							<li><a href=\"/shop/shopbrand.html?xcode=078&amp;type=N&amp;mcode=011\">니트</a></li>\r\n");
      out.write("							<li><a href=\"/shop/shopbrand.html?xcode=078&amp;type=N&amp;mcode=009\">맨투맨&amp;후드티</a></li>\r\n");
      out.write("							<li><a href=\"/shop/shopbrand.html?xcode=078&amp;type=N&amp;mcode=004\">긴팔티</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</span> \r\n");
      out.write("					\r\n");
      out.write("					<span class=\"tmenu\"> \r\n");
      out.write("						<a href=\"/shop/shopbrand.html?xcode=055&amp;type=Y\">SHIRTS</a>\r\n");
      out.write("						<ul class=\"depth2\" style=\"display: none;\">\r\n");
      out.write("							<li><a\r\n");
      out.write("								href=\"/shop/shopbrand.html?xcode=055&amp;type=N&amp;mcode=004\">베이직</a></li>\r\n");
      out.write("							<li><a\r\n");
      out.write("								href=\"/shop/shopbrand.html?xcode=055&amp;type=N&amp;mcode=006\">청남방</a></li>\r\n");
      out.write("							<li><a\r\n");
      out.write("								href=\"/shop/shopbrand.html?xcode=055&amp;type=N&amp;mcode=005\">체크&amp;패턴</a></li>\r\n");
      out.write("							<li><a\r\n");
      out.write("								href=\"/shop/shopbrand.html?xcode=055&amp;type=N&amp;mcode=003\">스트라이프</a></li>\r\n");
      out.write("							<li><a\r\n");
      out.write("								href=\"/shop/shopbrand.html?xcode=055&amp;type=N&amp;mcode=008\">헨리넥&amp;차이나</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</span> \r\n");
      out.write("					\r\n");
      out.write("					<span class=\"tmenu\"> \r\n");
      out.write("						<a href=\"/shop/shopbrand.html?xcode=081&amp;type=Y\">PANTS</a>\r\n");
      out.write("						<ul class=\"depth2\" style=\"display: none;\">\r\n");
      out.write("							<li><a\r\n");
      out.write("								href=\"/shop/shopbrand.html?xcode=081&amp;type=N&amp;mcode=006\">슬랙스</a></li>\r\n");
      out.write("							<li><a\r\n");
      out.write("								href=\"/shop/shopbrand.html?xcode=081&amp;type=N&amp;mcode=003\">면바지</a></li>\r\n");
      out.write("							<li><a\r\n");
      out.write("								href=\"/shop/shopbrand.html?xcode=081&amp;type=N&amp;mcode=002\">청바지</a></li>\r\n");
      out.write("							<li><a\r\n");
      out.write("								href=\"/shop/shopbrand.html?xcode=081&amp;type=N&amp;mcode=007\">밴딩팬츠</a></li>\r\n");
      out.write("							<li><a\r\n");
      out.write("								href=\"/shop/shopbrand.html?xcode=081&amp;type=N&amp;mcode=004\">반바지</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</span> \r\n");
      out.write("					\r\n");
      out.write("					<span class=\"tmenu\"> \r\n");
      out.write("						<a href=\"/shop/shopbrand.html?xcode=079&amp;type=Y\">OUTER</a>\r\n");
      out.write("						<ul class=\"depth2\" style=\"display: none;\">\r\n");
      out.write("							<li><a\r\n");
      out.write("								href=\"/shop/shopbrand.html?xcode=079&amp;type=N&amp;mcode=004\">패딩</a></li>\r\n");
      out.write("							<li><a\r\n");
      out.write("								href=\"/shop/shopbrand.html?xcode=079&amp;type=N&amp;mcode=002\">코트</a></li>\r\n");
      out.write("							<li><a\r\n");
      out.write("								href=\"/shop/shopbrand.html?xcode=079&amp;type=N&amp;mcode=006\">수트&amp;블레이져</a></li>\r\n");
      out.write("							<li><a\r\n");
      out.write("								href=\"/shop/shopbrand.html?xcode=079&amp;type=N&amp;mcode=010\">자켓</a></li>\r\n");
      out.write("							<li><a\r\n");
      out.write("								href=\"/shop/shopbrand.html?xcode=079&amp;type=N&amp;mcode=007\">블루종/MA-1</a></li>\r\n");
      out.write("							<li><a\r\n");
      out.write("								href=\"/shop/shopbrand.html?xcode=079&amp;type=N&amp;mcode=005\">가디건&amp;조끼</a></li>\r\n");
      out.write("							<li><a\r\n");
      out.write("								href=\"/shop/shopbrand.html?xcode=079&amp;type=N&amp;mcode=008\">후드&amp;집업</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</span> \r\n");
      out.write("					\r\n");
      out.write("					<span class=\"tmenu\"> \r\n");
      out.write("						<a href=\"/shop/shopbrand.html?xcode=083\">SHOES&amp;BAG</a>\r\n");
      out.write("						<ul class=\"depth2\" style=\"display: none;\">\r\n");
      out.write("							<li><a\r\n");
      out.write("								href=\"/shop/shopbrand.html?xcode=083&amp;type=N&amp;mcode=001\">신발</a></li>\r\n");
      out.write("							<li><a\r\n");
      out.write("								href=\"/shop/shopbrand.html?xcode=083&amp;type=N&amp;mcode=002\">가방</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</span> \r\n");
      out.write("					\r\n");
      out.write("					<span class=\"tmenu\"> \r\n");
      out.write("						<a href=\"/shop/shopbrand.html?xcode=080\">ACC</a>\r\n");
      out.write("						<ul class=\"depth2\" style=\"display: none;\">\r\n");
      out.write("							<li><a\r\n");
      out.write("								href=\"/shop/shopbrand.html?xcode=080&amp;type=N&amp;mcode=005\">양말&amp;타이</a></li>\r\n");
      out.write("							<li><a\r\n");
      out.write("								href=\"/shop/shopbrand.html?xcode=080&amp;type=N&amp;mcode=003\">모자</a></li>\r\n");
      out.write("							<li><a\r\n");
      out.write("								href=\"/shop/shopbrand.html?xcode=080&amp;type=N&amp;mcode=008\">벨트&amp;시계</a></li>\r\n");
      out.write("							<li><a\r\n");
      out.write("								href=\"/shop/shopbrand.html?xcode=080&amp;type=N&amp;mcode=006\">머플러&amp;장갑</a></li>\r\n");
      out.write("							<li><a\r\n");
      out.write("								href=\"/shop/shopbrand.html?xcode=080&amp;type=N&amp;mcode=002\">안경</a></li>\r\n");
      out.write("							<li><a\r\n");
      out.write("								href=\"/shop/shopbrand.html?xcode=080&amp;type=N&amp;mcode=004\">쥬얼리</a></li>\r\n");
      out.write("							<li><a\r\n");
      out.write("								href=\"/shop/shopbrand.html?xcode=080&amp;type=N&amp;mcode=007\">etc</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("			\r\n");
      out.write("					</span> \r\n");
      out.write("					\r\n");
      out.write("					<span class=\"tmenu\"> \r\n");
      out.write("						<a href=\"/shop/shopbrand.html?xcode=076\">SALE</a>\r\n");
      out.write("					</span> -->\r\n");
      out.write("				</div>\r\n");
      out.write("			</td> \r\n");
      out.write("			<td width=\"20%\">\r\n");
      out.write("				<div class=searchWrap>\r\n");
      out.write("					<form action=\"showSearchResult.jsp\" method=\"post\" name=\"search\">\r\n");
      out.write("						<span class=\"searchspan\"> \r\n");
      out.write("								<input name=\"search\" onkeydown=\"CheckKey_search();\" value=\"\" class=\"MS_search_word\"> \r\n");
      out.write("								<a href=\"javascript:search_submit();\" class=\"searhBtn\">\r\n");
      out.write("								<i class=\"xi-search\"></i>\r\n");
      out.write("								</a>\r\n");
      out.write("						</span> \r\n");
      out.write("							\r\n");
      out.write("						<span class=\"searchspan\"> 				\r\n");
      out.write("							<a href=\"/shop/shopbrand.html\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/images/btn_search.gif\"></a>\r\n");
      out.write("						</span>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</td> \r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Lato&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@500&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	/* 5 */\r\n");
      out.write("	.custom-btn {\r\n");
      out.write("	  background: #000;\r\n");
      out.write("	  color: #fff;\r\n");
      out.write("	  line-height: 42px;\r\n");
      out.write("	  padding: 0;\r\n");
      out.write("	  border: none;\r\n");
      out.write("	  font-size: 15px;\r\n");
      out.write("	  cursor:pointer;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	\r\n");
      out.write("	#userJoinTable{\r\n");
      out.write("		margin: auto;\r\n");
      out.write("		margin-top : 100px;\r\n");
      out.write("		text-align: left;\r\n");
      out.write("		width: 800x;\r\n");
      out.write("		border-spacing: 0 10px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#userJoinTable > caption{\r\n");
      out.write("		font-size: 19px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#userJoinTable p{\r\n");
      out.write("		margin: 0px;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("	var idUsable = \"\";  // null, POSSIBLE, IMPOSSIBLE\r\n");
      out.write("	\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("		//alert(1);\r\n");
      out.write("		\r\n");
      out.write("		//중복체크 버튼을 클릭했을 때\r\n");
      out.write("		$('#id_check').click(function(){\r\n");
      out.write("			\r\n");
      out.write("			if($('input[name=\"id\"]').val().length == 0){\r\n");
      out.write("				alert(\"아이디를 입력하세요\");\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("			else{\r\n");
      out.write("				$.ajax({ // 요청 자체를 화면을 이동하거나 하지 않으면서 할 수 있다는 장점이 있음\r\n");
      out.write("					url : \"id_check_proc.jsp\", //어디가서 처리결과를 가져올 건지 url을  지정\r\n");
      out.write("					data : {\r\n");
      out.write("						// 요청시 넘겨줄 데이터를 여기에 작성할 수 있음\r\n");
      out.write("						// 왼쪽에 위치한 변수는 내가 임의로 명명 가능\r\n");
      out.write("						// 이후에 id_check_proc.jsp 에서 request.getParameter(\"userid\") 로 접근가능 \r\n");
      out.write("						id : $('input[name=\"id\"]').val() // 사용자가 입력한 id\r\n");
      out.write("					},\r\n");
      out.write("					success : function(responseData){ // 인자에는  : 응답정보가 오는데 id_check_proc.jsp의 실행 결과가 넘어옴. 주석같은 것도 날라오기 때문에 id_check_proc.jsp 에서는 주석을 달면 안됨\r\n");
      out.write("						//alert('data: ' + $.trim(responseData)); \r\n");
      out.write("						idUsable = $.trim(responseData);\r\n");
      out.write("						\r\n");
      out.write("						if($.trim(responseData) == 'POSSIBLE'){ // 앞뒤에 붙은 공백을 제거해주고 비교해야 함. 					\r\n");
      out.write("							$('#id_message').html(\"<font color=blue>사용 가능합니다.</font>\");\r\n");
      out.write("							$('#id_message').show(); // 아래서 css('display', 'none') 한걸 다시 보이게 해줘야 함.\r\n");
      out.write("						}else{\r\n");
      out.write("							$('#id_message').html(\"<font color=red>이미 사용중인 아이디</font>\");\r\n");
      out.write("							$('#id_message').show();\r\n");
      out.write("						}\r\n");
      out.write("					}//success\r\n");
      out.write("				});//ajax	\r\n");
      out.write("			} // else\r\n");
      out.write("		});//중복체크 클릭의 끝\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		$('input[name=\"id\"]').keydown(function(){ //키보드가 한번이라도 눌리면 발생하는 이벤트 처리\r\n");
      out.write("			$('#id_message').css('display', 'none'); // 키가 눌렸을 때 안보이게.\r\n");
      out.write("			isChanged = true;\r\n");
      out.write("			ues=\"\"; // 새로운 데이터의 입력이 들어오면 상태 초기화\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("	});//ready\r\n");
      out.write("	\r\n");
      out.write("	function gotoRegisterProc(){\r\n");
      out.write("		\r\n");
      out.write("		if($('input[name=\"id\"]').val() == \"\"){\r\n");
      out.write("			alert(\"아이디를 입력하세요\");\r\n");
      out.write("			$('input[name=\"id\"]').focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if($('input[name=\"password\"]').val() == \"\"){\r\n");
      out.write("			alert(\"비밀번호를 입력하세요\");	\r\n");
      out.write("			$('input[name=\"password\"]').focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if($('input[name=\"re_password\"]').val() == \"\"){\r\n");
      out.write("			alert(\"비밀번호 확인을 입력하세요\");	\r\n");
      out.write("			$('input[name=\"re_password\"]').focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if($('input[name=\"password\"]').val() != $('input[name=\"re_password\"]').val()){\r\n");
      out.write("			alert(\"비밀번호가 일치하지 않습니다.\");		\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if($('input[name=\"name\"]').val() == \"\"){\r\n");
      out.write("			alert(\"이름을 입력하세요\");		\r\n");
      out.write("			$('input[name=\"name\"]').focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if($('input[name=\"rrn1\"]').val() == \"\"){\r\n");
      out.write("			alert(\"주민등록번호를 입력하세요\");	\r\n");
      out.write("			$('input[name=\"rrn1\"]').focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if($('input[name=\"rrn2\"]').val() == \"\"){\r\n");
      out.write("			alert(\"주민등록번호를 입력하세요\");	\r\n");
      out.write("			$('input[name=\"rrn2\"]').focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if( isNaN($('input[name=\"rrn1\"]').val())){\r\n");
      out.write("			alert(\"주민등록번호는 숫자만 입력 가능합니다\");\r\n");
      out.write("			$('input[name=\"rrn1\"]').select();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if( isNaN($('input[name=\"rrn2\"]').val())){\r\n");
      out.write("			alert(\"주민등록번호는 숫자만 입력 가능합니다\");\r\n");
      out.write("			$('input[name=\"rrn2\"]').select();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if($('input[name=\"hp1\"]').val() == \"\"){\r\n");
      out.write("			alert(\"전화번호를 입력하세요\");	\r\n");
      out.write("			$('input[name=\"hp1\"]').focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if($('input[name=\"hp2\"]').val() == \"\"){\r\n");
      out.write("			alert(\"전화번호를 입력하세요\");	\r\n");
      out.write("			$('input[name=\"hp2\"]').focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if($('input[name=\"hp3\"]').val() == \"\"){\r\n");
      out.write("			alert(\"전화번호를 입력하세요\");	\r\n");
      out.write("			$('input[name=\"hp3\"]').focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if( isNaN($('input[name=\"hp1\"]').val())){\r\n");
      out.write("			alert(\"전화번호는 숫자만 입력 가능합니다\");\r\n");
      out.write("			$('input[name=\"hp1\"]').select();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if( isNaN($('input[name=\"hp2\"]').val())){\r\n");
      out.write("			alert(\"전화번호는 숫자만 입력 가능합니다\");\r\n");
      out.write("			$('input[name=\"hp2\"]').select();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if( isNaN($('input[name=\"hp3\"]').val())){\r\n");
      out.write("			alert(\"전화번호는 숫자만 입력 가능합니다\");\r\n");
      out.write("			$('input[name=\"hp3\"]').select();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if($('input[name=\"zip\"]').val() == \"\"){\r\n");
      out.write("			alert(\"주소를 입력하세요\");	\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if($('input[name=\"addr2\"]').val() == \"\"){\r\n");
      out.write("			alert(\"상세주소를 입력하세요\");	\r\n");
      out.write("			$('input[name=\"addr2\"]').focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(idUsable == \"\"){\r\n");
      out.write("			alert(\"아이디 중복체크를 수행해주세요\");\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(idUsable == \"IMPOSSIBLE\"){\r\n");
      out.write("			alert(\"아이디 중복여부를 확인하세요\");\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		var reg = /^[a-zA-Z0-9]{3,10}$/;\r\n");
      out.write("		\r\n");
      out.write("		var tempId = $('input[name=\"id\"]').val();\r\n");
      out.write("		if(tempId.search(reg) == -1){\r\n");
      out.write("			alert(\"아이디는 3~10자의 영문, 숫자만 가능합니다\");\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		var tempPw = $('input[name=\"password\"]').val();\r\n");
      out.write("		if(tempPw.search(reg) == -1){\r\n");
      out.write("			alert(\"비밀번호는 3~10자의 영문, 숫자만 가능합니다\");\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		document.f.submit();\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("	var newJquery = $.noConflict(true); // 다른 라이브러리랑 겹칠때 이렇게 해주면 됨.\r\n");
      out.write("	function openZipSearch() {\r\n");
      out.write("		new daum.Postcode({\r\n");
      out.write("			oncomplete: function(data) {\r\n");
      out.write("				newJquery('[name=zip]').val(data.zonecode); // 우편번호 (5자리)\r\n");
      out.write("				newJquery('[name=addr1]').val(data.address);\r\n");
      out.write("				newJquery('[name=addr2]').val(data.buildingName);\r\n");
      out.write("				newJquery('[name=addr2]').focus();\r\n");
      out.write("			}\r\n");
      out.write("		}).open();\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<form name=f action=\"./userJoinProc.jsp\" method=\"post\">\r\n");
      out.write("	<table id=\"userJoinTable\">\r\n");
      out.write("		<caption>\r\n");
      out.write("		SIGN UP\r\n");
      out.write("		<hr>\r\n");
      out.write("		</caption>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td><b>아이디</b></td>\r\n");
      out.write("			<td><input type=\"text\" name=\"id\" style=\"width:150px\" maxlength=\"10\" placeholder=\"3~10자의 영문, 숫자\"> \r\n");
      out.write("				<input type=\"button\" id=\"id_check\" value=\"중복체크\" style=\"height :22px;\">\r\n");
      out.write("				<span id=\"id_message\" style=\"font-size:13px\"></span>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td><b>비밀번호</b></td>\r\n");
      out.write("			<td><input type=\"password\" name=\"password\" maxlength=\"8\" style=\"width:150px\" placeholder=\"3~10자의 영문, 숫자\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td><b>비밀번호 확인</b></td>\r\n");
      out.write("			<td><input type=\"password\" name=\"re_password\" maxlength=\"8\" style=\"width:150px\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td><b>성명</b></td>\r\n");
      out.write("			<td><input type=\"text\" name=\"name\" style=\"width:150px\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td><b>주민등록번호</b></td>\r\n");
      out.write("			<td><input type=\"text\" maxlength=\"6\" name=\"rrn1\" style=\"width:60px\"> - <input type=\"text\" maxlength=\"7\" name=\"rrn2\" style=\"width:70px\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td valign=\"top\"><b>연락처</b></td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<input type=\"text\" maxlength=\"3\" name=\"hp1\" style=\"width:30px\"> - <input type=\"text\" maxlength=\"4\" name=\"hp2\" style=\"width:40px\"> - <input type=\"text\" maxlength=\"4\" name=\"hp3\" style=\"width:40px\">\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td valign=\"top\"><b>주소</b></td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<p><input type=\"text\" name=\"zip\" style=\"width:60px\" readonly> <input type=\"button\" value=\"우편번호\" onclick=\"openZipSearch()\"></p>\r\n");
      out.write("				<p><input type=\"text\" name=\"addr1\" style = \"margin-top: 10px;\" readonly> <input type=\"text\" name=\"addr2\"></p>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td colspan=\"8\"><br><input type=\"button\" value=\"회원가입\" class=\"custom-btn\" onClick=\"gotoRegisterProc()\" style=\"width:100%; height:50px\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("</form>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
